### ISSUE TITLE
Input files update

### ISSUE THREAD

**Issue by jjkoehorst** [mibwurrepo/Microbial-bioinformatics-introductory-course-Material-2018#1]
We need to test a dataset used with the current latest version of NG-Tax.
Wasin might be able to provide with such a set?

**Comment by microsud** [comment]
@jjkoehorst Somehow I missed your comment. Now sure if providing raw sequence data is ideal here. We use the already available test data from Human microbiome project output from QIIME. Using in-house datasets processed using NG-Tax from our lab may not be possible due to obvious reasons.

**Comment by jjkoehorst** [comment]
Could you give me the raw data that you currently use? Have been looking at https://portal.hmpdacc.org/ but there is no easy download beside a client and not sure which datasets you specifically use.

**Comment by microsud** [comment]
I have used already processed biom file and use the phyloseq object. The
sample size is large https://qiita.ucsd.edu/study/description/1927
The phyloseq object  can be found in this repository as .RDS file.

**Comment by microsud** [comment]
Now updated to test data set processed using NG-Tax
