### ISSUE TITLE
network analysis SPIEC-EASI code?

### ISSUE THREAD

**Issue by marwa38** [mibwurrepo/Microbial-bioinformatics-introductory-course-Material-2018#10]
Hello 

Thanks very much for sharing this course workflow for analysing microbiome studies.
Is there any possibility to let me know how to work with  SPIEC-EASI code used for network analysis after deprecating some parts of the function? 
`net.c <- spiec.easi(otu.c, method='mb', icov.select.params=list(rep.num=50))  `

Many Thanks 
Marwa

**Comment by microsud** [comment]
Hi Marwa! Unfortunately I have not used the latest version of SPIEC-EASI tool. May be the latest documentation of the pkg https://github.com/zdk123/SpiecEasi has relevant guidelines.
