### ISSUE TITLE
Fix the link to List of R tools for microbiome analysis

### ISSUE THREAD

**Issue by microsud** [mibwurrepo/Microbial-bioinformatics-introductory-course-Material-2018#5]
The section 1.2 Useful functions/resources has link to List of R tools for microbiome analysis. A typo in the repository name for List of R tools for microbiome analysis website. Now the link is broken in book. correct link is [here](https://microsud.github.io/Tools-Microbiome-Analysis/)

**Comment by mibwurmoleco** [comment]
Now fixed.
