### ISSUE TITLE
Can NG-Tax 2.0 still be accessed through Galaxy? 

### ISSUE THREAD

**Issue by TvdBosch** [mibwurrepo/Microbial-bioinformatics-introductory-course-Material-2018#6]
Having a user interface during the course was pretty convenient. I was wondering if NG-Tax can still be accessed through Galaxy, and if so, on what web address?  I searched through all of the course material and did a fair shair of Googling, but I haven't been able to find the Galaxy-version of NG-Tax anymore. Does it still exist? 
(I could only find https://galaxy.wur.nl/galaxy_production/ but that does not include NG-Tax in its tools.)

**Comment by jjkoehorst** [comment]
Hello,

It is still available via:

http://www.systemsbiology.nl/ngtax <http://www.systemsbiology.nl/ngtax>

Cheers,

Jasper

**Comment by TvdBosch** [comment]
Thank you very much!
