### ISSUE TITLE
Error: Failed to install 'microbiomeutilities' from GitHub:

### ISSUE THREAD

**Issue by holisim** [mibwurrepo/Microbial-bioinformatics-introductory-course-Material-2018#8]
i'm about to get ready with the course but i encounter this error:
Error: Failed to install 'microbiomeutilities' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘Rcpp’
would you kindly help?

**Comment by microsud** [comment]
Thanks for the msg. Please restart the r session and try to install again. The rcpp pkg is attached to the environment and sometimes such pkg attachment gives error If required for GitHub pkg. Hope it helps!

Cheers,
Sudarshan

**Comment by holisim** [comment]
@microsud 
thank you Sudarshan. I've got it done!! :)
