### ISSUE TITLE
error when making a pairwise list that we want to compare

### ISSUE THREAD

**Issue by Jasminehls** [mibwurrepo/Microbial-bioinformatics-introductory-course-Material-2018#9]
dear Sir,

i've encounter the following error code

Error in combn(seq_along(lev), 2, simplify = FALSE, FUN = function(i) lev[i]) : 
  n < m

when i run the following code:
> L.pairs <- combn(seq_along(lev), 2, simplify = FALSE, FUN = function(i) lev[i])

it was all ok until this step.

would you kindly help?

thank you.

**Comment by microsud** [comment]
Hi @Jasminehls ,
Thanks for the query. Could you please elaborate on the error. Was this error with test tutorial data or with your private data? 

Best wishes,
Sudarshan

**Comment by Jasminehls** [comment]
Hi Sudarshan ,

It was the test tutorial data, I basically just follow step by step, using the copy function to copy the code. It was all ok until this step.

Thank you.
Li sim

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by microsud** [comment]
Hi @Jasminehls 
I am unable to recreate the error. I use the same code:
`L.pairs <- combn(seq_along(lev), 2, simplify = FALSE, FUN = function(i) lev[i])`

And below is the system setup I used. Does it match yours? I have not tested the tutorial on R 4.0.0 version. Can you set up the same versions I use and see if the error persists?
> R version 3.6.3 (2020-02-29)

> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 18363)
> 
> Matrix products: default
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] dplyr_0.8.5                 data.table_1.12.8           DT_0.13                    
> [4] ggpubr_0.3.0                RColorBrewer_1.1-2          microbiomeutilities_0.99.02
> [7] microbiome_1.8.0            ggplot2_3.3.0               phyloseq_1.30.0            
> 
> loaded via a namespace (and not attached):
>  [1] nlme_3.1-147        ggsci_2.9           tools_3.6.3         backports_1.1.7    
>  [5] R6_2.4.1            vegan_2.5-6         BiocGenerics_0.32.0 mgcv_1.8-31        
>  [9] colorspace_1.4-1    permute_0.9-5       ade4_1.7-15         withr_2.2.0        
> [13] tidyselect_1.1.0    gridExtra_2.3       curl_4.3            compiler_3.6.3     
> [17] Biobase_2.46.0      labeling_0.3        scales_1.1.1        stringr_1.4.0      
> [21] digest_0.6.25       foreign_0.8-75      rmarkdown_2.1       rio_0.5.16         
> [25] XVector_0.26.0      pkgconfig_2.0.3     htmltools_0.4.0     htmlwidgets_1.5.1  
> [29] rlang_0.4.6         readxl_1.3.1        rstudioapi_0.11     farver_2.0.3       
> [33] generics_0.0.2      jsonlite_1.6.1      crosstalk_1.1.0.1   zip_2.0.4          
> [37] car_3.0-7           magrittr_1.5        biomformat_1.14.0   Matrix_1.2-18      
> [41] Rcpp_1.0.4.6        munsell_0.5.0       S4Vectors_0.24.4    Rhdf5lib_1.8.0     
> [45] ape_5.3             abind_1.4-5         viridis_0.5.1       lifecycle_0.2.0    
> [49] yaml_2.2.1          stringi_1.4.6       carData_3.0-3       MASS_7.3-51.6      
> [53] zlibbioc_1.32.0     rhdf5_2.30.1        Rtsne_0.15          plyr_1.8.6         
> [57] grid_3.6.3          parallel_3.6.3      ggrepel_0.8.2       forcats_0.5.0      
> [61] crayon_1.3.4        lattice_0.20-41     Biostrings_2.54.0   haven_2.2.0        
> [65] splines_3.6.3       multtest_2.42.0     hms_0.5.3           knitr_1.28         
> [69] pillar_1.4.4        igraph_1.2.5        ggsignif_0.6.0      reshape2_1.4.4     
> [73] codetools_0.2-16    stats4_3.6.3        glue_1.4.1          evaluate_0.14      
> [77] vctrs_0.3.0         foreach_1.5.0       cellranger_1.1.0    gtable_0.3.0       
> [81] purrr_0.3.4         tidyr_1.0.3         assertthat_0.2.1    xfun_0.13          
> [85] openxlsx_4.1.5      broom_0.5.6         rstatix_0.5.0       survival_3.1-12    
> [89] viridisLite_0.3.0   tibble_3.0.1        pheatmap_1.0.12     iterators_1.0.12   
> [93] IRanges_2.20.2      cluster_2.1.0       ellipsis_0.3.1 

`

**Comment by Jasminehls** [comment]
Hi Sudarshan,

Thank you.

I am using R version 4.0.0 as I could not find the source to download R version 3.6.3

I shall try to download R 3.6.3 and try again.

Will update you on the outcome.

Regards,
Li Sim, Jasminehls

**Comment by Jasminehls** [comment]
Hi Sudarshan,

Yes you are right, no issues with R 3.6.3

Thanks!

Regards,
Li Sim
